DROP DATABASE IF EXISTS secretary_app;
CREATE DATABASE IF NOT EXISTS secretary_app;
USE secretary_app;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  hash VARCHAR(255) NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE NOT NULL
);

USE secretary_app;
UPDATE users SET is_admin = TRUE WHERE name = 'tj';
